# This file is part of project Sverchok. It's copyrighted by the contributors
# recorded in the version control history of the file, available from
# its original location https://github.com/nortikin/sverchok/commit/master
#  
# SPDX-License-Identifier: GPL3
# License-Filename: LICENSE

sv_no_ve = [[(3, -1, 0),  (1, -1, 0),  (1, 2, 0),  (4, 2, 0),  (-1, -1, 0), 
  (0, -1, 0),  (1, 0, 0),  (0, 2, 0),  (-1, 2, 0),  (-1, 0, 0),  (0, 0, 0), 
  (3, 2, 0),  (2, 2, 0),  (3, 0, 0),  (3, 1, 0),  (7, -1, 0),  (8, -1, 0),  
  (7, 2, 0),  (10, 2, 0),  (5, -1, 0),  (6, -1, 0),  (7, 0, 0),  (7, 1, 0), 
  (6, 2, 0),  (5, 2, 0),  (5, 0, 0),  (5, 1, 0),  (10, 0, 0),  (10, 1, 0),  
  (9, 2, 0),  (8, 2, 0),  (8, 0, 0),  (8, 1, 0),  (9, 0, 0)]]   

sv_no_ed = [[[12, 11],  [5, 1],  [11, 3],  [5, 4],  [6, 1],  [7, 2],    
  [8, 7],  [9, 8],  [10, 9],  [6, 10],  [14, 11],  [13, 0],  [14, 13],  
  [30, 29],  [20, 15],  [22, 17],  [29, 18],  [28, 27],  [20, 19],  
  [21, 15],  [22, 21],  [23, 17],  [24, 23],  [26, 24],  [25, 19],  
  [26, 25],  [28, 18],  [32, 30],  [31, 16],  [32, 31],  [33, 31],  
  [27, 33]]]

list_formulaX = [    
    'i*XX',    
    '(i/100)',  
    '(i**2)*XX',    
    'sqrt(i*XX)',   
    'sin(XX)',  
    'sin(i*XX)',    
    'sin(i*XX+i**2)',   
    'sin(i)/(XX+cos(i))',   
    'sin(cos(i*XX))',   
    'sin(i)*cos(i)*i*XX',   
    'sin(i)*i*XX',  
    'cos(XX)',  
    'cos(i*XX)',    
    'cos(i)*i*XX',  
    '(cos(i)**2)*i*XX', 
    'cos(i*XX)**3', 
    'cos(i/2)*i*XX-cos(i/2)',   
    'cos(i*XX+i**2)',   
    'cos(i)*i*XX',  
    'cos(i*XX)',    
    'tan(i*XX)',    
    'tan(sin(i*XX))',   
    'tan(cos(XX*i**2))',    
    'atan(cos(i*XX))',  
    'XX*log((1+ sin(i)))',  
    #sphere 
    'cos(XX) * cos(YY)',    
    'cos(XX) * sin(XX)',    
    'sin(XX) * cos(YY)',    
    'sin(XX) * sin(YY)',    
    'sin(YY) * sin(YY)',    
    'log(exp(sin(XX)) * exp(cos(YY))',  
    'log(exp(sin(XX)) * exp(sin(YY))',  
    'exp(cos(XX))', 
    'sin(XX) * atan(YY)',   
    'tan(XX) * atan(YY)',   
    'sin(YY) * sin(YY) * sin(XX)',  
    'sin(XX) * sin(YY) * sin(YY)',  
    'sin(YY) * sin(YY) * cos(XX)',  
    'sin(XX) * cos(YY) * cos(YY)',  
    'sin(XX) * cos(YY) * sin(YY)',  
    'sin(YY) * cos(YY) * sin(YY)',  
    'sin(XX) * cos(YY) * log(YY, 2)/10',    
    'sin(YY) * cos(YY) * cos(XX)'
]    

list_formulaY = [
   'i*YY', 
    '(i/100)',  
    '(i**2)*YY',    
    'sqrt(i*YY)',   
    'sin(YY)',  
    'sin(i*YY)',    
    'sin(i*YY+i**2)',   
    'sin(i)/(YY+cos(i))',   
    'sin(cos(i*YY))',   
    'sin(i)*cos(i)*i*YY',   
    'sin(i)*i*YY',  
    'cos(YY)',  
    'cos(i*YY)',    
    'cos(i)*i*YY',  
    '(cos(i)**2)*i*YY', 
    'cos(i*YY)**3', 
    'cos(i/2)*i*YY-cos(i/2)',   
    'cos(i*YY+i**2)',   
    'cos(i)*i*YY',  
    'cos(i*YY)',    
    'tan(i*YY)',    
    'tan(sin(i*YY))',   
    'tan(cos(YY*i**2))',    
    'atan(cos(i*YY))',  
    'YY*log((1+ sin(i)))',  
    #sphere 
    'cos(XX) * cos(YY)',    
    'cos(XX) * sin(XX)',    
    'sin(XX) * cos(YY)',    
    'sin(XX) * sin(YY)',    
    'sin(YY) * sin(YY)',    
    'log(exp(sin(XX)) * exp(cos(YY))',  
    'log(exp(sin(XX)) * exp(sin(YY))',  
    'exp(cos(XX))', 
    'sin(XX) * atan(YY)',   
    'tan(XX) * atan(YY)',   
    'sin(YY) * sin(YY) * sin(XX)',  
    'sin(XX) * sin(YY) * sin(YY)',  
    'sin(YY) * sin(YY) * cos(XX)',  
    'sin(XX) * cos(YY) * cos(YY)',  
    'sin(XX) * cos(YY) * sin(YY)',  
    'sin(YY) * cos(YY) * sin(YY)',  
    'sin(XX) * cos(YY) * log(YY, 2)/10',    
    'sin(YY) * cos(YY) * cos(XX)'
]    

list_formulaZ = [
    'i*ZZ', 
    '(i/100)',  
    '(i**2)*ZZ',    
    'sqrt(i*ZZ)',   
    'sin(ZZ)',  
    'sin(i*ZZ)',    
    'sin(i*ZZ+i**2)',   
    'sin(i)/(ZZ+cos(i))',   
    'sin(cos(i*ZZ))',   
    'sin(i)*cos(i)*i*ZZ',   
    'sin(i)*i*ZZ',  
    'cos(ZZ)',  
    'cos(i*ZZ)',    
    'cos(i)*i*ZZ',  
    '(cos(i)**2)*i*ZZ', 
    'cos(i*ZZ)**3', 
    'cos(i/2)*i*ZZ-cos(i/2)',   
    'cos(i*ZZ+i**2)',   
    'cos(i)*i*ZZ',  
    'cos(i*ZZ)',    
    'tan(i*ZZ)',    
    'tan(sin(i*ZZ))',   
    'tan(cos(ZZ*i**2))',    
    'atan(cos(i*ZZ))',  
    'ZZ*log((1+ sin(i)))',  
    #sphere 
    'cos(XX) * cos(YY)',    
    'cos(XX) * sin(XX)',    
    'sin(XX) * cos(YY)',    
    'sin(XX) * sin(YY)',    
    'sin(YY) * sin(YY)',    
    'log(exp(sin(XX)) * exp(cos(YY))',  
    'log(exp(sin(XX)) * exp(sin(YY))',  
    'exp(cos(XX))', 
    'sin(XX) * atan(YY)',   
    'tan(XX) * atan(YY)',   
    'sin(YY) * sin(YY) * sin(XX)',  
    'sin(XX) * sin(YY) * sin(YY)',  
    'sin(YY) * sin(YY) * cos(XX)',  
    'sin(XX) * cos(YY) * cos(YY)',  
    'sin(XX) * cos(YY) * sin(YY)',  
    'sin(YY) * cos(YY) * sin(YY)',  
    'sin(XX) * cos(YY) * log(YY, 2)/10',    
    'sin(YY) * cos(YY) * cos(XX)'
]

list_X_X = [    
    'XX',   
    'i',    
    'i**2', 
    'pi*i', 
    'i*i*pi',   
    'i/pi', 
    'pi/i', 
    'i*XX', 
    'i/XX', 
    'XX/i', 
    'XX*pi*i',  
    'XX/i/pi',  
    'XX/pi*i',  
    'i*pi/XX',  
    'i/pi*XX',  
    'pi/i*XX',  
    'i*XX/pi',  
    '1/i*XX*pi',    
    # logs  
    'log(pi*i)+XX', 
    'log(i*1)/tan(XX*i)*50',    
    '12/pi*log(i)*XX',  
    '2*pi*log(i)*XX',   
    # trigono   
    'tan(i)',   
    'sin(i)',   
    'cos(i)',   
    'sin(XX/pi*i)', 
    'sin(tan(XX*i))*50',    
    'cos(XX*pi*i)', 
    'tan(XX*i*pi)', 
    'tan(i)*XX'
]

list_Y_Y = [    
    'YY',
    'i',    
    'i**2', 
    'pi*i', 
    'i*i*pi',   
    'i/pi', 
    'pi/i', 
    'i*YY', 
    'i/YY', 
    'YY/i', 
    'YY*pi*i',  
    'YY/i/pi',  
    'YY/pi*i',  
    'i*pi/YY',  
    'i/pi*YY',  
    'pi/i*YY',  
    'i*YY/pi',  
    '1/i*YY*pi',    
    # logs  
    'log(pi*i)+YY', 
    'log(i*1)/tan(YY*i)*50',    
    '12/pi*log(i)*YY',  
    '2*pi*log(i)*YY',   
    # trigono   
    'tan(i)',   
    'sin(i)',   
    'cos(i)',   
    'sin(YY/pi*i)', 
    'sin(tan(YY*i))*50',    
    'cos(YY*pi*i)', 
    'tan(YY*i*pi)', 
    'tan(i)*YY'
]

list_Z_Z = [   
    'ZZ',   
    'i',    
    'i**2', 
    'pi*i', 
    'i*i*pi',   
    'i/pi', 
    'pi/i', 
    'i*ZZ', 
    'i/ZZ', 
    'ZZ/i', 
    'ZZ*pi*i',  
    'ZZ/i/pi',  
    'ZZ/pi*i',  
    'i*pi/ZZ',  
    'i/pi*ZZ',  
    'pi/i*ZZ',  
    'i*ZZ/pi',  
    '1/i*ZZ*pi',    
    # logs  
    'log(pi*i)+ZZ', 
    'log(i*1)/tan(ZZ*i)*50',    
    '12/pi*log(i)*ZZ',  
    '2*pi*log(i)*ZZ',   
    # trigono   
    'tan(i)',   
    'sin(i)',   
    'cos(i)',   
    'sin(ZZ/pi*i)', 
    'sin(tan(ZZ*i))*50',    
    'cos(ZZ*pi*i)', 
    'tan(ZZ*i*pi)', 
    'tan(i)*ZZ',    
]

# EOF