nodes_dict = {'analyzer': ['area',
                           'bbox',
                           'distance_pp',
                           'polygons_centers',
                           'kd_tree',
                           'kd_tree_edges'],
              'basic_view': ['bakery',
                        'test',
                        'viewer_bmesh',
                        'viewer_indices',
                        'viewer_text',
                        'viewer',
                        'empty_out',
                        'reroute'],
              'basic_data': ['objects',
                        'text',
                        'wifi_in',
                        'wifi_out',
                        'eval_knieval',],
              'basic_debug': ['debug_print',
                        'frame_info',
                        'gtext',
                        'note',
                        '3dview_props',
                        'viewer_node_editor_bgl',],
              'generator': ['box',
                            'circle',
                            'cylinder',
                            'hilbert_image',
                            'hilbert',
                            'hilbert3d',
                            'image',
                            'line',
                            'plane',
                            'random_vector',
                            'script',
                            'formula',
                            'sphere',
                            'basic_spline',
                            'basic_3pt_arc'],
              'list_basic': ['converter',
                       'decompose',
                       'func',
                       'join',
                       'length',
                       'levels',
                       'mask_join',
                       'mask',
                       'match',
                       'sum',
                       'zip'],
              'list_interfere': ['shift',
                       'repeater',
                       'slice',
                       'split',
                       'start_end',
                       'item',
                       'reverse',
                       'shuffle',
                       'sort',
                       'flip'],
              'matrix': ['apply',
                         'deform',
                         'destructor',
                         'generator',
                         'input',
                         'interpolation',
                         'shear'],
              'modifier_change': ['delete_loose',
                           'edges_intersect',
                           'holes_fill',
                           'mesh_join',
                           'mesh_separate',
                           'polygons_boom',
                           'polygons_to_edges',
                           'remove_doubles',
                           'vertices_mask'],
              'modifier_make': ['bisect',
                           'convex_hull',
                           'cross_section',
                           'edges_adaptative',
                           'lathe',
                           'line_connect',
                           'polygons_adaptative',
                           'solidify',
                           'voronoi_2d',
                           'voronoi',
                           'offset',
                           'wireframe'],
              'number': ['float_to_int',
                         'float',
                         'integer',
                         'random',
                         'formula',
                         'formula2',
                         'scalar',
                         'list_input',
                         'range_map',
                         'range',
                         'range_float',
                         'range_int',
                         'series'],
              'vector': ['drop',
                         'interpolation',
                         'line_evaluate',
                         'math',
                         'move',
                         'noise',
                         'normal',
                         'vector_in',
                         'vector_out',
                         'vertices_delete_doubles',
                         'vertices_sort',
                         'axis_input']
              }

