# -*- coding: utf-8 -*-
# ##### BEGIN GPL LICENSE BLOCK #####
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# ##### END GPL LICENSE BLOCK #####

import os
import sverchok
import bpy

"""
this file hopes to allow simple access (via an autogenerated menu) to 
custom nodes which are stored in:
    <your path>datafiles/sverchok/user_nodes/..

    <datafiles/sverchok..> is found using
        datafiles = os.path.join(bpy.utils.user_resource('DATAFILES', path='sverchok', create=True))

"""

def get_user_nodes_dir():
    datafiles = os.path.join(bpy.utils.user_resource('DATAFILES', path='sverchok', create=True))
    user_nodes_path = os.path.join(datafiles, "user_nodes")

    drop_me = ["__init__.py", "__pycache__"]

    
